spring:
  application:
    name: ExcelGenerator
  servlet:
    multipart:
      max-file-size: 10MB        # ?? ?? ?? ??
      max-request-size: 50MB     # ?? ?? ?? ?? (?? ?? ??? ?)
      enabled: true

server:
  servlet:
    session:
      timeout: 120m  # ?? ?? ?? 120?